version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://usr:12345@db/process_mapping_db
    ports:
      - '8000:8000'
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres
    environment:
      - POSTGRES_USER=usr
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=process_mapping_db
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data


volumes:
  postgres: